### ISSUE TITLE
Plugin development flow and distribution

### ISSUE THREAD

**Issue by adriandmitroca** [monetivo/monetivo-woocommerce#1]
Hi guys,

At the very beginning - great work with Monetivo. It's awesome to see that folks from Poznań build awesome products like yours.

I've reviewed some source code of yours WooCommerce plugin from simple curiosity after thinking about committing suicide from working with official _WooCommerce Przelewy24 Gateway_ and here are some of my thoughts that could help you guys improve your product and make it easier to develop without much effort.

- [x] Abandon maintaining whole `monetivo-woocommerce/source/wp-content/plugins/monetivo-woocommerce/` tree. It should be just `monetivo-woocommerce` with plugin's source code inside. You shouldn't actually make the user find an actual directory to copy.
- [x] Ship your plugin on official page as a `.zip` file. Most of the users aren't developers and they want to install your payment gateway using two ways: 

     - WordPress Plugin Directory 
     - Ready to install ZIP file

   Even if the user would be an actual developer, he wouldn't be able to pull this repository through Composer because of incorrect flow, so none of the benefits are available right now.
- [x] Don't maintain your official PHP SDK in multiple places. I see that code under `monetivo-woocommerce/source/wp-content/plugins/monetivo-woocommerce/includes/client/` is already outdated in compare to `monetivo/monetivo-php`. Use benefits of Composer instead and pull SDK library inside WooCommerce's plugin. It won't be a problem for users since you provide ready to install builds from the point above anyway.

That's all, I didn't check direct integration with WooCommerce though. Hope that you will consider my issue a little valuable.

Cheers!

**Comment by gagacinski** [comment]
Hi @adriandmitroca!

Thank you for your input in developing our plugin and sorry for such delayed response!
All your ideas (and more) have been implemented in release 1.1.0.

Should you have any more, please issue them to us!

Cheers!
